Module3 task1
htmlacademy-react/1621345-what-to-watch-5 pull request #7
Opened 2020-11-04 03:22 UTC by rim1sta

2020-11-08 11:17 UTC, vatokato requested changes
Привет, вижу ты разобрался, молодец.
несколько мелких замечаний. В целом же все отлично.

2020-11-08 11:17 UTC, vatokato commented on src/components/films-list/films-list.jsx
> +  onCardHover: PropTypes.func.isRequired,
onCardHover и onCardBlur приходят не из пропсов, не нужно описывать

2020-11-08 11:17 UTC, vatokato commented on src/components/main-page/main-page.jsx
> +  movieInfo: PropTypes.arrayOf(movieShape).isRequired,
movieInfo - это не массив, это просто объект с данными, проп тайпс задан не верно

2020-11-08 11:17 UTC, vatokato commented on src/components/app/app.jsx
> +  film: filmShape,
film не приходит в пропсах, лишнее.

2020-11-08 11:17 UTC, vatokato commented on src/components/add-comment/add-comment.jsx
> +  handleSubmit: PropTypes.func.isRequired,
обработчики не приходят в пропсах, не нужно их валидировать

2020-11-09 17:41 UTC, rim1sta commented on src/index.js
>  );
исправил

2020-11-09 17:41 UTC, rim1sta commented on src/components/films-list/films-list.jsx
> +  onCardHover: PropTypes.func.isRequired,
+

2020-11-09 17:41 UTC, rim1sta commented on src/components/main-page/main-page.jsx
> +  movieInfo: PropTypes.arrayOf(movieShape).isRequired,
+

2020-11-09 17:41 UTC, rim1sta commented on src/components/app/app.jsx
> +  film: filmShape,
+

2020-11-09 17:41 UTC, rim1sta commented on src/components/add-comment/add-comment.jsx
> +  handleSubmit: PropTypes.func.isRequired,
+

2020-11-09 17:49 UTC, vatokato commented on src/index.js
> +  movieInfo: PropTypes.shape(movieShape).isRequired,
опять у тебя шейп в шейпе )
`movieInfo: movieShape.isRequired,`

2020-11-09 17:49 UTC, vatokato commented on src/components/main-page/main-page.jsx
> +  movieInfo: PropTypes.shape(movieShape).isRequired,
опять у тебя шейп в шейпе )
`movieInfo: movieShape.isRequired,`

2020-11-09 17:49 UTC, vatokato commented on src/components/app/app.jsx
> +  movieInfo: PropTypes.shape(movieShape).isRequired,
опять у тебя шейп в шейпе )
`movieInfo: movieShape.isRequired,`

2020-11-09 17:50 UTC, vatokato commented on src/components/app/app.jsx
> +          <>
знак подсвечивается, не знаю что это, попробуй заменить на `div` или на фрагмент

2020-11-11 13:44 UTC, rim1sta commented on src/index.js
> +  movieInfo: PropTypes.shape(movieShape).isRequired,
исправил

2020-11-11 13:45 UTC, rim1sta commented on src/components/main-page/main-page.jsx
> +  movieInfo: PropTypes.shape(movieShape).isRequired,
исправил

2020-11-11 13:45 UTC, rim1sta commented on src/components/app/app.jsx
> +  movieInfo: PropTypes.shape(movieShape).isRequired,
исправил

2020-11-11 13:45 UTC, rim1sta commented on src/components/app/app.jsx
> +          <>
исправил

2020-11-12 03:23 UTC, vatokato commented
Все отлично. Молодец что сумел найти все проблемы и исправить их

2020-11-12 03:23 UTC, merged